version: "3"

services: 
    webapp:
        build: 
            context: .
            dockerfile: Dockerfile
        
        command: gunicorn Myblog.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - static_volume:/home/app/web/static_collected
        expose: 
            - 8000
        env_file:
            - ./.env.prod
        depends_on:
            - db
    
    db:
        image: postgres:12.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file: 
            - ./.env.prod.db
        ports:
            - "5432:5432"
    
    nginx:
        build: ./nginx
        volumes:
            - static_volume:/home/app/web/static_collected
        ports: 
            - 1337:80
        depends_on: 
            - webapp
  
volumes:
    postgres_data:
    static_volume: