# Generated by Django 2.1.5 on 2019-01-24 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_passage'),
    ]

    operations = [
        migrations.AddField(
            model_name='passage',
            name='title',
            field=models.CharField(default='abc', max_length=200),
        ),
    ]
