# Generated by Django 2.1.5 on 2019-01-24 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_passage_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passage',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
