# Generated by Django 2.1.5 on 2019-01-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190126_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='passage',
            name='pic_url',
            field=models.CharField(default='blog/pictures/21.jpg', max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
