# Generated by Django 2.1.5 on 2019-01-29 13:20

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190129_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passage',
            name='text',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
